; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = three_slot


[env]
monitor_filters = time, log2file, esp32_exception_decoder
platform = espressif32 
board = esp32doit-devkit-v1
board_build.partitions = partition_custom.csv
framework = arduino
debug_tool = esp-prog
debug_init_break = tbreak setup
lib_deps = 
	knolleary/pubsubclient
	adafruit/RTClib@^1.14.2
	bblanchon/ArduinoJson@^6.21.4
	https://github.com/Neubolt/Firebase-ESP32-Client.git
	ESP32Async/ESPAsyncWebServer @^3.7.7
	adafruit/Adafruit GFX Library@^1.11.7
	https://github.com/Neubolt/ESP32Ping.git
	https://github.com/nhatuan84/esp32-sh1106-oled
	https://github.com/junhuanchen/Esp32-SoftwareSerial
upload_speed = 921600
monitor_speed = 115200

[env:single_slot]
build_flags = -DCORE_DEBUG_LEVEL=5 -D NUM_OF_SLOTS=1

[env:double_slot]
build_flags = -DCORE_DEBUG_LEVEL=5 -D NUM_OF_SLOTS=2

[env:three_slot]
build_flags = -DCORE_DEBUG_LEVEL=5 -D NUM_OF_SLOTS=3


